INSERT INTO TBL_PRODUCT  (PRICE, NOME)  VALUES (10, 'ARROZ');
INSERT INTO TBL_PRODUCT (PRICE, NOME)  VALUES  (5,'FEIJAO');
INSERT INTO TBL_PRODUCT  (PRICE, NOME)  VALUES (20,'CARNE');
INSERT INTO TBL_PRODUCT  (PRICE, NOME)  VALUES (2,'MAÇÃ');

